### ISSUE TITLE
Inquiry about running a demo using a custom trained model

### ISSUE THREAD

**Issue by sinfone** [Ruyi-Zha/naf_cbct#10]
After following the training instructions, I have successfully trained my own model using my custom dataset. I would like to use the trained model to perform a demo and generate CT images. Could you please provide some guidance on how to proceed?
Thank you in advance for your assistance.

**Comment by Ruyi-Zha** [comment]
Hi, thanks for your interest. During training, the predicted CT image, ground-truth CT image, and some slice demos will be saved in `logs/*/eval/epoch_*`. You can easily write a script to visualize and perform a demo. Unfortunately, we do not have a specific test script, but you can look at lines 77-90 in `train.py` for reference.
