### ISSUE TITLE
Can you help me explain this function “angle2pose”？Can you provide the coordinate system relationships in the paper?

### ISSUE THREAD

**Issue by hyaihjq** [Ruyi-Zha/naf_cbct#12]

**Comment by Ruyi-Zha** [comment]
Hi, the function `angle2pose` computes the coordinate of the X-ray source in the world frame based on its rotation angle. Our coordinate system is similar to that in TIGRE toolbox, except for the detector plane which follows OpenCV standards. Here is a diagram. Hope this helps.

![coord](https://github.com/Ruyi-Zha/naf_cbct/assets/50566530/d901f259-8b37-4868-9a12-a20c22f032e3)

**Comment by hyaihjq** [comment]
thanks!
