### ISSUE TITLE
the effect of last_activation 

### ISSUE THREAD

**Issue by wanghongjian98** [Ruyi-Zha/naf_cbct#19]
Hi, I have a problem choosing the last_activation, I saw you put the   last_activation: **relu** fir abdomen_50 and sigmoid for others,

**Comment by Ruyi-Zha** [comment]
Thank you for your interest in our work. Both ReLU and sigmoid functions should work fine. If the target data range is within [0,1], then you can use the sigmoid function. Otherwise, ReLU is a choice.
