### ISSUE TITLE
FDK baseline

### ISSUE THREAD

**Issue by zhouzhenghong-gt** [Ruyi-Zha/naf_cbct#2]
Thanks for your great work!!!
May I ask how to get the baseline result of FDK? Is it through python or matlab code?

**Comment by Ruyi-Zha** [comment]
Hi, thanks for your interest. We use [TIGRE](https://github.com/CERN/TIGRE) toolbox to get baseline results. You can check [this script](https://github.com/CERN/TIGRE/blob/master/Python/demos/d06_Algorithms01.py) for FDK.
