### ISSUE TITLE
Regarding the Dataset Training Volume

### ISSUE THREAD

**Issue by LeoZhongLinYang** [Ruyi-Zha/naf_cbct#22]
Regarding the Dataset Training Volume

Hello, I would like to ask about the foot dataset. You used 50 projections generated from a single volumetric CT scan for training, and then used the same volumetric CT scan for testing. Wouldn't this mean that the training and testing are sharing the same information? Could this approach be incorrect?

Thank you!

**Comment by Ruyi-Zha** [comment]
Hi, our task is self-supervised, aiming at reconstructing arbitrary object from its multi-view projections. This is different from those supervised learning methods that require an external dataset for pre-training.

During training, we use 2D projections only. During testing, we compare our predicted volumes with the ground truth. The training and testing processes are independent; we don't use testing outcomes to influence the training. Testing simply serves to evaluate the reconstruction quality.

**Comment by LeoZhongLinYang** [comment]
Hello, thank you very much for your reply, I understand now.
However, I still have one question: Did you achieve the results mentioned in the paper by using only a single volumetric CT scan (e.g., foot)? I only see four types of data in your dataset, with one for each type. I am curious if you trained on any other data that is not included in the dataset.

**Comment by Ruyi-Zha** [comment]
Our method makes no assumptions about the target volume, allowing it to work with arbitrary objects. Recent papers, such as [SAX-NeRF](https://arxiv.org/abs/2311.10959),and [R2-Gaussian](https://arxiv.org/abs/2405.20693)) also demonstrate that NAF can be applied across a broader range of object categories.

**Comment by LeoZhongLinYang** [comment]
Thank you very much for your reply and for providing the paper. I completely understand now. I apologize for taking up so much of your time, and I really appreciate and admire your research outcomes.
