### ISSUE TITLE
How to evaluate？

### ISSUE THREAD

**Issue by xuyaojian123** [Ruyi-Zha/naf_cbct#23]
请问一下，比如对于Teapot场景，它的原始数据只有它对应的投影图像和CT扫描的元配置文件.xtekct。那么我如何评价重建后的效果？因为原始数据中没有真实的三维volume CT数据。
![image](https://github.com/user-attachments/assets/9990fe64-becd-45df-97bb-57ee1c904e08)

![image](https://github.com/user-attachments/assets/572c1ad6-1dc2-4647-aad5-274f56fc11e4)

![image](https://github.com/user-attachments/assets/4691631a-8018-46db-93e9-5fcac54f76b8)

**Comment by Ruyi-Zha** [comment]
在这种情况下无法简单地定量地评估重建质量。如果你有teapot的三维模型（比如mesh），可以通过从CT volume中提取mesh模型来进行定量评估。否则只能通过观察重建结果来定性评估。

**Comment by xuyaojian123** [comment]
好的，谢谢你的解答！原始数据没有它的任何三维模型。
