### ISSUE TITLE
How to evaluate CT volume？

### ISSUE THREAD

**Issue by xuyaojian123** [Ruyi-Zha/naf_cbct#24]
真实的三维CT volume数据是` img.mat`，你通过`def get_voxels(self, geo: ConeGeometry)`函数得到三维体素网格的坐标，然后输入网络得到坐标对应的density。那请问一下get_voxels得到的三维体素坐标和img.mat是如何对应上的，他们对应的是同一个世界坐标位置吗？

![image](https://github.com/user-attachments/assets/9b93519a-0788-4a25-9bae-cd52d736c060)

**Comment by Ruyi-Zha** [comment]
是的他们对应同一个坐标系。geo存储了整个场景的结构信息。sVoxel是被重建CT volume的大小，dVoxel是每个小体素的大小。减去的1/2 dVoxel使得被query的坐标位于每个小体素的中心。

**Comment by xuyaojian123** [comment]
好的，谢谢您的回答！
那这个前提是世界坐标系的原点得是在真实的三维CT volume的中心位置吧？还有想问下，论文里面的相机坐标系（`Our coordinate system is similar to that in TIGRE toolbox, except for the detector plane which follows OpenCV standards.`）是和opencv/colmap一样的嘛？你说的成像平面的except for the detector plane which follows OpenCV standards是什么意思呢？
![image](https://github.com/user-attachments/assets/211b9b8c-49f7-4028-891f-08dd379dcb37)

![image](https://github.com/user-attachments/assets/007dfe27-1ff6-42f1-88d3-0df8eab611c6)

**Comment by Ruyi-Zha** [comment]
1. 感谢你的提醒，`get_voxels()`的代码里voxel的位置还需要加上CT volume的中心位置，即`geo.offOrigin`。只需要最后再添加一个`xyz=xyz+geo.offOrigin`即可。我稍后会修改这个bug。在我们的数据里，CT volume位于`(0,0,0)`的位置，所以实验结果不受影响。

2. 可以和TIGRE的坐标系对比一下。他们的图像原点位于左下角，u轴朝右，v轴朝上。我们选择使用opencv标准，原点位于左上角，x轴（u轴）朝右，y轴（v轴）朝下。这么做的好处是我们可以将xray source和detector类比成相机，以此更方便后续的计算和推导。

TIGRE
![image](https://github.com/user-attachments/assets/9dd98e47-9ed1-4fe5-9a7c-ce76e60ac17c)

**Comment by xuyaojian123** [comment]
感谢解答

**Comment by xuyaojian123** [comment]
佬，能加个联系方式嘛？最近我在研究这个X-Ray图像重建，看了一些论文NeAT，NaF，SAF-NeRF论文，对CT数据其实还有些困惑，周围没有做这个方向的人讨论。不会打扰到你，就是可能偶尔咨询你一下，我的vx：18679338489。后面会把这条评论删除。
