### ISSUE TITLE
Hyperparameter settings

### ISSUE THREAD

**Issue by he0713** [Ruyi-Zha/naf_cbct#28]
The pair ray selection in the paper is 2048 but the config in the code is 1024, why is that? Hope you can answer, thanks.

**Comment by Ruyi-Zha** [comment]
Hi, the code does not fully align with the paper, as it has been updated multiple times. Experimentally, we’ve found that using 1024 achieves similar performance, so we’ve chosen to use it for efficiency.

**Comment by he0713** [comment]
Thank you for your answer.
