### ISSUE TITLE
About CUDA version and other environmental configurations

### ISSUE THREAD

**Issue by LeoZhongLinYang** [Ruyi-Zha/naf_cbct#5]
Hello, I have encountered the following error while configuring the environment

No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6'

So I would like to configure the environment to your version for network training, thank you very much!

**Comment by Ruyi-Zha** [comment]
Hi, sorry for the late response. I have updated `README.md` and you can find more detailed instructions on configuring environments.

One note is that the `hash encoder` module that we use from [torch-ngp](https://github.com/ashawkey/torch-ngp.git) only supports CUDA <= v11.3. I tried CUDA v11.6 and encountered the problem you mentioned as well. Therefore I suggest using CUDA v11.3 for convenience as mentioned in `README.md`.

Thanks.

**Comment by ben2k** [comment]
Even with Cuda 11.3 it looks like there is compilation issues:

/usr/local/cuda-11.3/bin/nvcc  -DTORCH_EXTENSION_NAME=_hash_encoder -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/imfusion/anaconda3/envs/naf/lib/python3.9/site-packages/torch/include -isystem /home/imfusion/anaconda3/envs/naf/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/imfusion/anaconda3/envs/naf/lib/python3.9/site-packages/torch/include/TH -isystem /home/imfusion/anaconda3/envs/naf/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda-11.3/include -isystem /home/imfusion/anaconda3/envs/naf/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -O3 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -std=c++14 -c /home/imfusion/Documents/naf_cbct/src/encoder/hashencoder/src/hashencoder.cu -o hashencoder.cuda.o
/home/imfusion/Documents/naf_cbct/src/encoder/hashencoder/src/hashencoder.cu(26): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (__half *, c10::Half)

**Comment by Ruyi-Zha** [comment]
It appears the issue may be related to your CUDA version or GPU architecture. We tested the code on a 3090, and it worked fine. You may check [this link](https://forums.developer.nvidia.com/t/why-does-atomicadd-not-work-with-doubles-as-input/56429) for help.
